@extends('curriculum.layout')

@section('style')
    
@endsection

@section('content')
    <div id="curriculum">
        <div id="table-scroll">
            <table >
                <thead>
                    <tr>
                        <th></th>
                        <th>一</th>
                        <th>二</th>
                        <th>三</th>
                        <th>四</th>
                        <th>五</th>
                        <th>六</th>
                        <th>日</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>A</td>
                        <td>1-A</td>
                        <td>2-A</td>
                        <td>3-A</td>
                        <td>4-A</td>
                        <td>5-A</td>
                        <td>6-A</td>
                        <td>7-A</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>1-1</td>
                        <td>2-1</td>
                        <td>3-1</td>
                        <td>4-1</td>
                        <td>5-1</td>
                        <td>6-1</td>
                        <td>7-1</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>1-2</td>
                        <td class="blueClass">跨領域文跨領域文跨領域文跨領域文跨領域文跨領域文</td>
                        <td>3-2</td>
                        <td>4-2</td>
                        <td>5-2</td>
                        <td>6-2</td>
                        <td>7-2</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>1-3</td>
                        <td class="blueClass">跨領域文</td>
                        <td>3-3</td>
                        <td>4-3</td>
                        <td>5-3</td>
                        <td>6-3</td>
                        <td>7-3</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>1-4</td>
                        <td class="blueClass">跨領域文</td>
                        <td>3-4</td>
                        <td>4-4</td>
                        <td>5-4</td>
                        <td>6-4</td>
                        <td>7-4</td>
                    </tr>
                    <tr>
                        <td>B</td>
                        <td>1-B</td>
                        <td>2-B</td>
                        <td>3-B</td>
                        <td>4-B</td>
                        <td>5-B</td>
                        <td>6-B</td>
                        <td>7-B</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>1-5</td>
                        <td>2-5</td>
                        <td>3-5</td>
                        <td>4-5</td>
                        <td>5-5</td>
                        <td>6-5</td>
                        <td>7-5</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>1-6</td>
                        <td>2-6</td>
                        <td>3-6</td>
                        <td>4-6</td>
                        <td>5-6</td>
                        <td>6-6</td>
                        <td>7-6</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>1-7</td>
                        <td>2-7</td>
                        <td>3-7</td>
                        <td>4-7</td>
                        <td>5-7</td>
                        <td>6-7</td>
                        <td>7-7</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>1-8</td>
                        <td>2-8</td>
                        <td>3-8</td>
                        <td>4-8</td>
                        <td>5-8</td>
                        <td>6-8</td>
                        <td>7-8</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>1-9</td>
                        <td>2-9</td>
                        <td>3-9</td>
                        <td>4-9</td>
                        <td>5-9</td>
                        <td>6-9</td>
                        <td>7-9</td>
                    </tr>
                    <tr>
                        <td>C</td>
                        <td>1-C</td>
                        <td>2-C</td>
                        <td>3-C</td>
                        <td>4-C</td>
                        <td>5-C</td>
                        <td>6-C</td>
                        <td>7-C</td>
                    </tr>
                    <tr>
                        <td>D</td>
                        <td>1-D</td>
                        <td>2-D</td>
                        <td>3-D</td>
                        <td>4-D</td>
                        <td>5-D</td>
                        <td>6-D</td>
                        <td>7-D</td>
                    </tr>
                    <tr>
                        <td>E</td>
                        <td>1-E</td>
                        <td>2-E</td>
                        <td>3-E</td>
                        <td>4-E</td>
                        <td>5-E</td>
                        <td>6-E</td>
                        <td>7-E</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection